function checkTxz(){
		$.ajax({
			type:'POST',
			url:'http://i.cmge.com/oauth/GetSSOLogined',
			jsonpCallback:'sso_check',
			dataType:'jsonp',
			data:{time:1,sign:'sign'},
			success:function(data){
				if(data.status){
						noticeSelf(data);
				}else{
					if(logined){
						$.getJSON(logoutUrl,{},function(result){
							if(result.status=='success'){
								if(result.value.html&&$("#userinfo").length>0){
									$("#userinfo").html(result.value.html);
								}else{
								location.reload();
								}
							}
						})
					}
				}
			}
		});
	}
	function noticeSelf(user){
		if(noticeLoginUrl != undefined && noticeLoginUrl != ''&&user.status){ 
			$.ajax({
				url:noticeLoginUrl,
				data:{user:user},
				success:function(result){
					if(result.status=='success'){
						if(result.value.html&&$("#userinfo").length>0){
							$("#userinfo").html(result.value.html);
						}else{
						location.reload();
						}
					}
				},
				type:'POST',
				dataType:'json'
			})
		}
	}
	function txzLogout(){
		$.ajax({
			type:'POST',
			url:'http://i.cmge.com/oauth/Logout',
			jsonpCallback:'sso_check',
			dataType:'jsonp',
			data:{time:1,sign:'sign'},
			success:function(data){
				if(data.status&&logoutUrl){
					$.getJSON(logoutUrl,{},function(result){
						if(result.status=='success'){
							if(result.value.html&&$("#userinfo").length>0){
								$("#userinfo").html(result.value.html);
							}else{
							    location.reload();
							}
						}
					})
				}
			}
		});
	}
$(function(){
	$(document).ready(function(){
		checkTxz();
	});
})