document.writeln('<div class="plant_hed_nav_hover">');
document.writeln('<a href="javascript:void(0);" class="next_nav"><span id="ico_yx">&nbsp;</span>全部游戏</a>');
document.writeln('<div style="height: 0px; width: 0px;" class="next_div"><div class="next_div_top"></div>');
document.writeln('<div class="next_div_cot"><div class="newxt_div_cott"><div class="next_gamelist">');
document.writeln('<h3>客户端游戏</h3><ul>');
document.writeln('<li><a href="http://tera.kunlun.com/" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">TERA</a></li>');
document.writeln('<li><a href="http://seal.kunlun.com/" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">希望OL</a></li>');
document.writeln('<li><a href="http://q.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/BB.jpg">晴空物语</a></li>');
document.writeln('<li><a href="http://ro.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/BB.jpg">仙境传说</a></li>');
document.writeln('<li><a href="http://fm.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">伏魔者</a></li>');
document.writeln('<li><a href="http://hy.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">黄易群侠传2</a></li>');
document.writeln('<li><a href="http://fn.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">圣境传说</a></li>');
document.writeln('<li></li></ul></div><div class="next_gamelist"><h3>战争策略</h3><ul>');
document.writeln('<li><a href="http://sg2.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">三国风云2</a></li>');
document.writeln('<li><a href="http://qjp.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">千军破</a></li>');
document.writeln('<li><a href="http://sg.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">三国风云</a></li>');
document.writeln('<li><a href="http://qjp2.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/BB.jpg">千军破2</a></li>');
document.writeln('<li></li><li></li><li></li><li></li></ul></div>');
document.writeln('<div class="next_gamelist next_gamelist_special"><h3>角色扮演</h3><ul>');
document.writeln('<li><a href="http://jd.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">武侠外传</a></li>');
document.writeln('<li><a href="http://fs.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">封神无双</a></li>');
document.writeln('<li></li><li></li><li></li><li></li><li></li><li></li></ul><ul>');
document.writeln('<li><a href="http://xj.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">仙境幻想</a></li>');
document.writeln('<li><a href="http://wx.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">武侠风云</a></li>');
document.writeln('<li></li><li></li><li></li><li></li><li></li><li></li></ul></div>');
document.writeln('<div class="next_gamelist"><h3>手机游戏</h3><ul>');
document.writeln('<li><a href="http://bb.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">海岛奇兵</a></li>');
document.writeln('<li><a href="http://jhzr.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">剑魂之刃</a></li>');
document.writeln('<li><a href="http://mt.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">超级MT</a></li>');
document.writeln('<li><a href="http://fkbl.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/NN.jpg">疯狂部落</a></li>');
document.writeln('<li><a href="http://mobi.kunlun.com/xb/web.html" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">仙变</a></li>');
document.writeln('<li><a href="http://wxqz.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">武侠Q传</a></li>');
document.writeln('<li><a href="http://wxwz.kunlun.com" target="_blank"><img src="http://item.kunlun.com/top/images/HH.jpg">武侠外传</a></li>');
document.writeln('<li></li></ul></div></div></div></div>');
document.writeln('</div>');
